// Dados de teste para desenvolvimento do frontend

export const mockPlanos = [
  {
    id: 1,
    nome: "Concurso TRF - Analista Judiciário",
    descricao: "Plano completo para o concurso do Tribunal Regional Federal",
    tipo: "pago" as const,
    duracaoTotal: 180,
    concursoArea: "Tribunais",
    ativo: 1,
    horasDiariasPadrao: 4,
    diasEstudoPadrao: "1,2,3,4,5",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: 2,
    nome: "Concurso SEFAZ - Auditor Fiscal",
    descricao: "Preparação intensiva para Auditor Fiscal da Receita Estadual",
    tipo: "pago" as const,
    duracaoTotal: 240,
    concursoArea: "Fiscal",
    ativo: 1,
    horasDiariasPadrao: 6,
    diasEstudoPadrao: "1,2,3,4,5,6",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const mockMetas = [
  {
    id: 1,
    planoId: 1,
    disciplina: "Direito Constitucional",
    assunto: "Direitos e Garantias Fundamentais",
    tipo: "estudo" as const,
    duracao: 90,
    incidencia: "alta" as const,
    prioridade: 5,
    ordem: 1,
    dicaEstudo: "Foque nos artigos 5º ao 17º da CF/88. Faça resumos e mapas mentais.",
    aulaId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    planoId: 1,
    disciplina: "Direito Administrativo",
    assunto: "Princípios da Administração Pública",
    tipo: "estudo" as const,
    duracao: 60,
    incidencia: "alta" as const,
    prioridade: 5,
    ordem: 2,
    dicaEstudo: "Memorize os princípios LIMPE: Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência.",
    aulaId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    planoId: 1,
    disciplina: "Português",
    assunto: "Interpretação de Textos",
    tipo: "questoes" as const,
    duracao: 45,
    incidencia: "media" as const,
    prioridade: 4,
    ordem: 3,
    dicaEstudo: "Resolva 15 questões de interpretação. Anote os erros e revise.",
    aulaId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    planoId: 1,
    disciplina: "Raciocínio Lógico",
    assunto: "Lógica Proposicional",
    tipo: "estudo" as const,
    duracao: 60,
    incidencia: "media" as const,
    prioridade: 3,
    ordem: 4,
    dicaEstudo: "Estude tabelas-verdade e conectivos lógicos. Pratique com exercícios.",
    aulaId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    planoId: 1,
    disciplina: "Direito Constitucional",
    assunto: "Direitos e Garantias Fundamentais",
    tipo: "revisao" as const,
    duracao: 30,
    incidencia: "alta" as const,
    prioridade: 5,
    ordem: 5,
    dicaEstudo: "Revise seus resumos e mapas mentais. Faça questões de fixação.",
    aulaId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    planoId: 1,
    disciplina: "Informática",
    assunto: "Segurança da Informação",
    tipo: "estudo" as const,
    duracao: 45,
    incidencia: "baixa" as const,
    prioridade: 2,
    ordem: 6,
    dicaEstudo: "Estude os principais tipos de malware e técnicas de proteção.",
    aulaId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockAulas = [
  {
    id: 1,
    titulo: "Direitos e Garantias Fundamentais - Aula Completa",
    descricao: "Análise detalhada dos direitos fundamentais previstos na Constituição Federal de 1988, com foco em questões de concursos.",
    professorId: 1,
    disciplina: "Direito Constitucional",
    assuntoNivel1: "Direitos Fundamentais",
    assuntoNivel2: "Direitos e Garantias",
    assuntoNivel3: "Artigo 5º",
    concursoArea: "Tribunais",
    duracao: 120,
    tipoConteudo: "videoaula" as const,
    urlVideo: "https://example.com/video1",
    urlMaterial: null,
    conteudoHtml: null,
    tags: JSON.stringify(["direitos fundamentais", "CF88", "artigo 5º"]),
    nivelDificuldade: "intermediario" as const,
    visualizacoes: 1245,
    ativo: 1,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: 2,
    titulo: "Princípios da Administração Pública",
    descricao: "Estudo aprofundado dos princípios constitucionais e legais que regem a Administração Pública brasileira.",
    professorId: 2,
    disciplina: "Direito Administrativo",
    assuntoNivel1: "Princípios",
    assuntoNivel2: "Princípios Constitucionais",
    assuntoNivel3: null,
    concursoArea: "Tribunais",
    duracao: 90,
    tipoConteudo: "videoaula" as const,
    urlVideo: "https://example.com/video2",
    urlMaterial: null,
    conteudoHtml: null,
    tags: JSON.stringify(["LIMPE", "princípios", "administração pública"]),
    nivelDificuldade: "basico" as const,
    visualizacoes: 2103,
    ativo: 1,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: 3,
    titulo: "Lógica Proposicional - Fundamentos",
    descricao: "Introdução à lógica proposicional: conectivos, tabelas-verdade e equivalências lógicas.",
    professorId: 3,
    disciplina: "Raciocínio Lógico",
    assuntoNivel1: "Lógica",
    assuntoNivel2: "Lógica Proposicional",
    assuntoNivel3: "Conectivos",
    concursoArea: "Geral",
    duracao: 75,
    tipoConteudo: "videoaula" as const,
    urlVideo: "https://example.com/video3",
    urlMaterial: null,
    conteudoHtml: null,
    tags: JSON.stringify(["lógica", "proposições", "tabela-verdade"]),
    nivelDificuldade: "basico" as const,
    visualizacoes: 987,
    ativo: 1,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: 4,
    titulo: "Segurança da Informação - Conceitos Básicos",
    descricao: "Principais conceitos de segurança da informação: confidencialidade, integridade, disponibilidade e tipos de ameaças.",
    professorId: 4,
    disciplina: "Informática",
    assuntoNivel1: "Segurança",
    assuntoNivel2: "Conceitos Básicos",
    assuntoNivel3: null,
    concursoArea: "Geral",
    duracao: 60,
    tipoConteudo: "videoaula" as const,
    urlVideo: "https://example.com/video4",
    urlMaterial: null,
    conteudoHtml: null,
    tags: JSON.stringify(["segurança", "malware", "proteção"]),
    nivelDificuldade: "basico" as const,
    visualizacoes: 654,
    ativo: 1,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: 5,
    titulo: "Interpretação de Textos - Técnicas Avançadas",
    descricao: "Técnicas e estratégias para resolver questões de interpretação de textos em concursos públicos.",
    professorId: 5,
    disciplina: "Português",
    assuntoNivel1: "Interpretação",
    assuntoNivel2: "Técnicas",
    assuntoNivel3: null,
    concursoArea: "Geral",
    duracao: 90,
    tipoConteudo: "videoaula" as const,
    urlVideo: "https://example.com/video5",
    urlMaterial: null,
    conteudoHtml: null,
    tags: JSON.stringify(["interpretação", "português", "técnicas"]),
    nivelDificuldade: "intermediario" as const,
    visualizacoes: 1876,
    ativo: 1,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
];

export const mockForumTopicos = [
  {
    id: 1,
    userId: 2,
    titulo: "Dúvida sobre Remédios Constitucionais",
    conteudo: "Alguém pode explicar a diferença entre Habeas Corpus e Habeas Data? Sempre confundo os dois.",
    categoria: "Direito Constitucional",
    tags: JSON.stringify(["remédios constitucionais", "HC", "HD"]),
    aulaId: 1,
    metaId: null,
    resolvido: 0,
    fixado: 0,
    fechado: 0,
    visualizacoes: 45,
    curtidas: 8,
    createdAt: new Date("2024-10-20"),
    updatedAt: new Date("2024-10-20"),
  },
  {
    id: 2,
    userId: 3,
    titulo: "Como memorizar os Princípios da Administração Pública?",
    conteudo: "Estou com dificuldade para decorar todos os princípios. Alguém tem alguma dica de mnemônico ou técnica?",
    categoria: "Direito Administrativo",
    tags: JSON.stringify(["princípios", "memorização", "dicas"]),
    aulaId: 2,
    metaId: null,
    resolvido: 1,
    fixado: 0,
    fechado: 0,
    visualizacoes: 123,
    curtidas: 15,
    createdAt: new Date("2024-10-22"),
    updatedAt: new Date("2024-10-23"),
  },
  {
    id: 3,
    userId: 4,
    titulo: "Questão sobre Tabela-Verdade",
    conteudo: "Na questão 45 da lista de exercícios, não entendi como chegar no gabarito. Alguém pode ajudar?",
    categoria: "Raciocínio Lógico",
    tags: JSON.stringify(["tabela-verdade", "exercício", "dúvida"]),
    aulaId: 3,
    metaId: null,
    resolvido: 0,
    fixado: 0,
    fechado: 0,
    visualizacoes: 67,
    curtidas: 5,
    createdAt: new Date("2024-10-25"),
    updatedAt: new Date("2024-10-25"),
  },
  {
    id: 4,
    userId: 5,
    titulo: "[IMPORTANTE] Mudança no Edital do TRF",
    conteudo: "Pessoal, saiu retificação no edital! Foram incluídos novos tópicos de Direito Tributário. Confiram!",
    categoria: "Avisos",
    tags: JSON.stringify(["edital", "mudança", "importante"]),
    aulaId: null,
    metaId: null,
    resolvido: 0,
    fixado: 1,
    fechado: 0,
    visualizacoes: 289,
    curtidas: 42,
    createdAt: new Date("2024-10-26"),
    updatedAt: new Date("2024-10-26"),
  },
  {
    id: 5,
    userId: 6,
    titulo: "Melhor ordem para estudar as disciplinas?",
    conteudo: "Para quem está começando agora, qual seria a melhor ordem para estudar as disciplinas do concurso?",
    categoria: "Dicas de Estudo",
    tags: JSON.stringify(["ordem", "disciplinas", "iniciante"]),
    aulaId: null,
    metaId: null,
    resolvido: 0,
    fixado: 0,
    fechado: 0,
    visualizacoes: 156,
    curtidas: 23,
    createdAt: new Date("2024-10-27"),
    updatedAt: new Date("2024-10-27"),
  },
];

export const mockMatricula = {
  id: 1,
  userId: 1,
  planoId: 1,
  dataInicio: new Date("2024-10-01"),
  dataTermino: new Date("2025-03-30"),
  horasDiarias: 4,
  diasEstudo: "1,2,3,4,5",
  ativo: 1,
  createdAt: new Date("2024-10-01"),
  updatedAt: new Date("2024-10-01"),
};

export const mockEstatisticas = {
  horasEstudadas: 28.5,
  metasConcluidas: 42,
  metasTotais: 85,
  aulasAssistidas: 15,
  questoesResolvidas: 234,
  taxaAcerto: 73,
  sequenciaDias: 7,
  mediaDiaria: 4.2,
};
