// Mock data para desenvolvimento e testes

export const mockPlanos = [
  {
    id: 1,
    nome: "Concurso TRF - Analista Judiciário",
    descricao: "Plano completo para o concurso do Tribunal Regional Federal",
    tipo: "pago" as const,
    duracaoTotal: 180,
    concursoArea: "Tribunais",
    ativo: 1,
    horasDiariasPadrao: 4,
    diasEstudoPadrao: "1,2,3,4,5",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: 2,
    nome: "Concurso SEFAZ - Auditor Fiscal",
    descricao: "Preparação intensiva para Auditor Fiscal da Receita Estadual",
    tipo: "pago" as const,
    duracaoTotal: 240,
    concursoArea: "Fiscal",
    ativo: 1,
    horasDiariasPadrao: 6,
    diasEstudoPadrao: "1,2,3,4,5,6",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const mockMetas = [
  {
    id: 1,
    planoId: 1,
    disciplina: "Direito Constitucional",
    assunto: "Direitos e Garantias Fundamentais",
    tipo: "estudo" as const,
    duracao: 90,
    incidencia: "alta" as const,
    prioridade: 5,
    ordem: 1,
    dicaEstudo: "Foque nos artigos 5º ao 17º da CF/88. Faça resumos e mapas mentais.",
    aulaId: 1,
    data: new Date("2025-01-27"),
    concluida: false,
    cor: "#3b82f6",
    anotacao: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    planoId: 1,
    disciplina: "Direito Administrativo",
    assunto: "Princípios da Administração Pública",
    tipo: "estudo" as const,
    duracao: 60,
    incidencia: "alta" as const,
    prioridade: 5,
    ordem: 2,
    dicaEstudo: "LIMPE: Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência.",
    aulaId: 2,
    data: new Date("2025-01-28"),
    concluida: true,
    cor: "#3b82f6",
    anotacao: "Revisei os 5 princípios básicos. Preciso aprofundar em Moralidade.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    planoId: 1,
    disciplina: "Direito Penal",
    assunto: "Teoria do Crime",
    tipo: "revisao" as const,
    duracao: 45,
    incidencia: "media" as const,
    prioridade: 3,
    ordem: 3,
    dicaEstudo: "Revise fato típico, antijurídico e culpável. Faça questões.",
    aulaId: 3,
    data: new Date("2025-01-28"),
    concluida: false,
    cor: "#8b5cf6",
    anotacao: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    planoId: 1,
    disciplina: "Direito Constitucional",
    assunto: "Organização do Estado",
    tipo: "questoes" as const,
    duracao: 60,
    incidencia: "alta" as const,
    prioridade: 4,
    ordem: 4,
    dicaEstudo: "Resolva 30 questões sobre federação, União, Estados e Municípios.",
    aulaId: null,
    data: new Date("2025-01-29"),
    concluida: false,
    cor: "#10b981",
    anotacao: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    planoId: 1,
    disciplina: "Direito Civil",
    assunto: "Pessoas Naturais e Jurídicas",
    tipo: "estudo" as const,
    duracao: 90,
    incidencia: "media" as const,
    prioridade: 3,
    ordem: 5,
    dicaEstudo: "Estude capacidade, personalidade e domicílio.",
    aulaId: 4,
    data: new Date("2025-01-30"),
    concluida: false,
    cor: "#3b82f6",
    anotacao: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    planoId: 1,
    disciplina: "Direito Processual Civil",
    assunto: "Princípios Processuais",
    tipo: "revisao" as const,
    duracao: 60,
    incidencia: "baixa" as const,
    prioridade: 2,
    ordem: 6,
    dicaEstudo: "Revise contraditório, ampla defesa e devido processo legal.",
    aulaId: 5,
    data: new Date("2025-01-31"),
    concluida: false,
    cor: "#8b5cf6",
    anotacao: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    planoId: 1,
    disciplina: "Direito Penal",
    assunto: "Crimes contra a Administração Pública",
    tipo: "questoes" as const,
    duracao: 75,
    incidencia: "alta" as const,
    prioridade: 5,
    ordem: 7,
    dicaEstudo: "Resolva questões sobre peculato, corrupção e prevaricação.",
    aulaId: null,
    data: new Date("2025-02-01"),
    concluida: false,
    cor: "#10b981",
    anotacao: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    planoId: 1,
    disciplina: "Direito Administrativo",
    assunto: "Atos Administrativos",
    tipo: "estudo" as const,
    duracao: 90,
    incidencia: "alta" as const,
    prioridade: 5,
    ordem: 8,
    dicaEstudo: "Estude atributos, elementos e classificação dos atos administrativos.",
    aulaId: 6,
    data: new Date("2025-02-02"),
    concluida: false,
    cor: "#3b82f6",
    anotacao: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockAulas = [
  {
    id: 1,
    titulo: "Direitos Fundamentais - Aula Completa",
    disciplina: "Direito Constitucional",
    professor: "Prof. João Silva",
    duracao: 120,
    tipo: "video" as const,
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    descricao: "Aula completa sobre direitos e garantias fundamentais previstos na Constituição Federal.",
    nivelDificuldade: "Intermediário" as const,
    createdAt: new Date(),
  },
  {
    id: 2,
    titulo: "Princípios da Administração Pública",
    disciplina: "Direito Administrativo",
    professor: "Prof. Maria Santos",
    duracao: 90,
    tipo: "video" as const,
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    descricao: "Estudo detalhado dos princípios constitucionais da administração pública.",
    nivelDificuldade: "Básico" as const,
    createdAt: new Date(),
  },
  {
    id: 3,
    titulo: "Teoria do Crime - PDF Resumo",
    disciplina: "Direito Penal",
    professor: "Prof. Pedro Costa",
    duracao: 30,
    tipo: "pdf" as const,
    url: "/materiais/teoria-crime.pdf",
    descricao: "Resumo esquematizado sobre a teoria do crime.",
    nivelDificuldade: "Avançado" as const,
    createdAt: new Date(),
  },
];


export const mockEstatisticas = {
  horasEstudadas: 28.5,
  metasConcluidas: 42,
  totalMetas: 85,
  aulasAssistidas: 15,
  questoesResolvidas: 234,
  taxaAcerto: 73,
  sequenciaDias: 7,
};

export const mockForumTopicos = [
  {
    id: 1,
    titulo: "Dúvida sobre Princípio da Legalidade",
    autor: "João Silva",
    disciplina: "Direito Administrativo",
    categoria: "Dúvidas",
    conteudo: "Gostaria de entender melhor a aplicação do princípio da legalidade nos atos administrativos. Alguém pode me ajudar?",
    respostas: 5,
    visualizacoes: 42,
    curtidas: 8,
    createdAt: new Date("2025-01-25"),
  },
  {
    id: 2,
    titulo: "Como estudar Direitos Fundamentais?",
    autor: "Maria Santos",
    disciplina: "Direito Constitucional",
    categoria: "Discussão",
    conteudo: "Pessoal, quais são as melhores técnicas para memorizar os direitos fundamentais? Estou com dificuldade.",
    respostas: 12,
    visualizacoes: 89,
    curtidas: 15,
    createdAt: new Date("2025-01-24"),
  },
  {
    id: 3,
    titulo: "Questão sobre Teoria do Crime",
    autor: "Pedro Costa",
    disciplina: "Direito Penal",
    categoria: "Questões",
    conteudo: "Encontrei uma questão que não consegui resolver sobre fato típico. Alguém pode explicar?",
    respostas: 3,
    visualizacoes: 28,
    curtidas: 4,
    createdAt: new Date("2025-01-26"),
  },
];
